// SPDX-License-Identifier: AGPL-3.0-or-later
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
public enum HTTPMethod:String,Codable,Sendable {case get="GET",post="POST",put="PUT",delete="DELETE"}
public struct EntryQuery:Equatable,Sendable {public var metricKey:String?;public var from:String?;public var to:String?;public var cursor:String?;public var limit:Int;public init(metricKey:String?=nil,from:String?=nil,to:String?=nil,cursor:String?=nil,limit:Int=50){self.metricKey=metricKey;self.from=from;self.to=to;self.cursor=cursor;self.limit=limit}}
public enum StatisticsPeriod:String,CaseIterable,Codable,Sendable {case thisWeek="this_week",lastWeek="last_week",last7Days="last_7_days",last30Days="last_30_days",thisMonth="this_month",lastMonth="last_month",thisYear="this_year",lastYear="last_year"}
public enum GoalPeriod:String,CaseIterable,Codable,Sendable {case day,week,month,longTerm="long_term"}
public enum APIEndpoint:Equatable,Sendable {
 case capabilities,configuration,dailyNote(String),dailyValues(String),dailyValue(metric:String,date:String),entries(EntryQuery),entry(Int64),measurements(from:String?,to:String?),measurement(Int64),routine(String),goals,goal(Int64),goalProgress(period:GoalPeriod,date:String?),statistics(period:StatisticsPeriod,metrics:[String]),statisticsViews,statisticsView(Int64)
 public var path:String{switch self{case .capabilities:return"ocs/v2.php/cloud/capabilities";case .configuration:return"ocs/v2.php/apps/health/api/v2/configuration";case .dailyNote(let d):return"ocs/v2.php/apps/health/api/v2/daily-notes/\(d)";case .dailyValues:return"ocs/v2.php/apps/health/api/v2/daily-values";case .dailyValue(let m,let d):return"ocs/v2.php/apps/health/api/v2/daily-values/\(m)/\(d)";case .entries:return"ocs/v2.php/apps/health/api/v2/entries";case .entry(let i):return"ocs/v2.php/apps/health/api/v2/entries/\(i)";case .measurements:return"ocs/v2.php/apps/health/api/v2/measurements";case .measurement(let i):return"ocs/v2.php/apps/health/api/v2/measurements/\(i)";case .routine(let c):return"ocs/v2.php/apps/health/api/v2/routines/\(c)";case .goals:return"ocs/v2.php/apps/health/api/v2/goals";case .goal(let i):return"ocs/v2.php/apps/health/api/v2/goals/\(i)";case .goalProgress:return"ocs/v2.php/apps/health/api/v2/goals/progress";case .statistics:return"ocs/v2.php/apps/health/api/v2/statistics";case .statisticsViews:return"ocs/v2.php/apps/health/api/v2/statistics/views";case .statisticsView(let i):return"ocs/v2.php/apps/health/api/v2/statistics/views/\(i)"}}
 public func url(on server:ServerConfiguration)throws->URL{var u=server.url;if !u.path.hasSuffix("/"){u.appendPathComponent("")};for c in path.split(separator:"/"){u.appendPathComponent(String(c))};var q:[URLQueryItem]=[];func add(_ n:String,_ v:String?){if let v,!v.isEmpty{q.append(.init(name:n,value:v))}};switch self{case .dailyValues(let date):add("date",date);case .entries(let x):add("metricKey",x.metricKey);add("from",x.from);add("to",x.to);add("cursor",x.cursor);add("limit",String(x.limit));case .measurements(let from,let to):add("from",from);add("to",to);case .goalProgress(let period,let date):add("period",period.rawValue);add("date",date);case .statistics(let period,let metrics):add("period",period.rawValue);add("metrics",metrics.joined(separator:","));default:break};if !q.isEmpty{var c=URLComponents(url:u,resolvingAgainstBaseURL:false)!;c.queryItems=q;u=c.url!};return u}}
public struct RequestBlueprint:Sendable{public let endpoint:APIEndpoint;public let method:HTTPMethod;public let body:Data?;public init(endpoint:APIEndpoint,method:HTTPMethod,body:Data?=nil){self.endpoint=endpoint;self.method=method;self.body=body};public func request(server:ServerConfiguration,authorization:String)throws->URLRequest{var r=URLRequest(url:try endpoint.url(on:server));r.httpMethod=method.rawValue;r.httpBody=body;r.setValue("true",forHTTPHeaderField:"OCS-APIRequest");r.setValue("application/json",forHTTPHeaderField:"Accept");r.setValue("application/json",forHTTPHeaderField:"Content-Type");r.setValue(authorization,forHTTPHeaderField:"Authorization");return r}}
