// SPDX-License-Identifier: AGPL-3.0-or-later
import Foundation
public enum MetricCategory:String,Codable,CaseIterable,Sendable {case journal,measurement,dailyValue="daily_value"}
public enum MetricValueType:String,Codable,Sendable {case scale,event,numeric,composite,counter}
public struct MetricDefinition:Codable,Hashable,Identifiable,Sendable {public var id:String{key};public let key:String;public let category:MetricCategory;public let valueType:MetricValueType;public let minimum:Double?;public let maximum:Double?;public let canonicalUnit:String?;public let supportedUnits:[String];public let options:[String];public let aggregation:String?
 enum CodingKeys:String,CodingKey {case key="metricKey",category,valueType,minimum,maximum,canonicalUnit,supportedUnits,options="allowedOptions",aggregation}
 public init(key:String,category:MetricCategory,valueType:MetricValueType,minimum:Double?=nil,maximum:Double?=nil,canonicalUnit:String?=nil,supportedUnits:[String]=[],options:[String]=[],aggregation:String?=nil){self.key=key;self.category=category;self.valueType=valueType;self.minimum=minimum;self.maximum=maximum;self.canonicalUnit=canonicalUnit;self.supportedUnits=supportedUnits;self.options=options;self.aggregation=aggregation}
 public init(from decoder:Decoder)throws {let c=try decoder.container(keyedBy:CodingKeys.self);key=try c.decode(String.self,forKey:.key);category=try c.decode(MetricCategory.self,forKey:.category);valueType=try c.decode(MetricValueType.self,forKey:.valueType);minimum=try c.decodeIfPresent(Double.self,forKey:.minimum);maximum=try c.decodeIfPresent(Double.self,forKey:.maximum);canonicalUnit=try c.decodeIfPresent(String.self,forKey:.canonicalUnit);supportedUnits=try c.decodeIfPresent([String].self,forKey:.supportedUnits) ?? [];options=try c.decodeIfPresent([String].self,forKey:.options) ?? [];aggregation=try c.decodeIfPresent(String.self,forKey:.aggregation)}
 public static let fallback:[MetricDefinition]=[
  .init(key:"stress",category:.journal,valueType:.scale,minimum:1,maximum:5),.init(key:"energy",category:.journal,valueType:.scale,minimum:1,maximum:5),.init(key:"mood",category:.journal,valueType:.scale,minimum:1,maximum:5),
  .init(key:"hydration",category:.journal,valueType:.event,options:["small_glass","large_glass","coffee","cappuccino","espresso","double_espresso","latte_macchiato","cafe_au_lait","tea","other"]),.init(key:"break",category:.journal,valueType:.event,options:["short","regular","short_walk","long_walk","mindfulness","fresh_air"]),
  .init(key:"temperature",category:.measurement,valueType:.numeric,canonicalUnit:"celsius",supportedUnits:["celsius","fahrenheit"]),.init(key:"oxygen_saturation",category:.measurement,valueType:.numeric,canonicalUnit:"percent",supportedUnits:["percent"]),.init(key:"blood_glucose",category:.measurement,valueType:.numeric,canonicalUnit:"mmol_l",supportedUnits:["mmol_l","mg_dl"]),.init(key:"pulse",category:.measurement,valueType:.numeric,canonicalUnit:"bpm",supportedUnits:["bpm"]),.init(key:"blood_pressure",category:.measurement,valueType:.composite,canonicalUnit:"mmhg",supportedUnits:["mmhg","kpa"]),
  .init(key:"weight",category:.dailyValue,valueType:.numeric,canonicalUnit:"kg",supportedUnits:["kg","lb","st"]),.init(key:"body_fat",category:.dailyValue,valueType:.numeric,canonicalUnit:"percent",supportedUnits:["percent"]),.init(key:"waist",category:.dailyValue,valueType:.numeric,canonicalUnit:"cm",supportedUnits:["cm","in"]),.init(key:"hip",category:.dailyValue,valueType:.numeric,canonicalUnit:"cm",supportedUnits:["cm","in"]),.init(key:"muscle_percentage",category:.dailyValue,valueType:.numeric,canonicalUnit:"percent",supportedUnits:["percent"]),.init(key:"sins",category:.dailyValue,valueType:.numeric,canonicalUnit:"count",supportedUnits:["count"]),.init(key:"steps",category:.dailyValue,valueType:.numeric,minimum:0,canonicalUnit:"steps",supportedUnits:["steps"]),.init(key:"kilocalories",category:.dailyValue,valueType:.numeric,minimum:0,canonicalUnit:"kcal",supportedUnits:["kcal"]),.init(key:"fruit",category:.dailyValue,valueType:.counter,minimum:0,canonicalUnit:"pieces",supportedUnits:["pieces"]),.init(key:"job_satisfaction",category:.dailyValue,valueType:.scale,minimum:1,maximum:5)]}
public struct DailyNote:Codable,Equatable,Sendable {public let date:String;public var content:String?;public let createdAt:String?;public let updatedAt:String?}
public struct DailyValue:Codable,Identifiable,Sendable {public let id:Int64;public let metricKey:String;public let numericValue:Double;public let localDate:String;public let createdAt:String?;public let updatedAt:String?;public let bmi:Double?}
public struct Entry:Codable,Identifiable,Sendable {public let id:Int64;public var metricKey:String;public var numericValue:Double?;public var optionValue:String?;public var context:String;public var source:String?;public var recordedAt:String;public var createdAt:String?;public var updatedAt:String?;public var note:String?}
public struct EntriesPage:Codable,Sendable {public let entries:[Entry];public let nextCursor:String?}
public struct Measurement:Codable,Identifiable,Sendable {public let id:Int64;public var metricKey:String;public var numericValue:Double?;public var values:[String:Double]?;public var context:String;public var source:String?;public var recordedAt:String;public var createdAt:String?;public var updatedAt:String?;public var note:String?}
public struct GoalRevision:Codable,Sendable {public let id:Int64?;public var comparator:String;public var targetValue:Double;public var secondaryTargetValue:Double?;public var effectiveFrom:String?;public var effectiveTo:String?}
public struct Goal:Codable,Identifiable,Sendable {public let id:Int64;public var targetKey:String;public var period:String;public var active:Bool;public var remindersEnabled:Bool;public var reminderPolicy:JSONValue?;public var retiredAt:String?;public var createdAt:String?;public var updatedAt:String?;public var currentRevision:GoalRevision?}
public struct GoalTarget:Codable,Identifiable,Sendable {public var id:String{targetKey};public let targetKey:String;public let metricKey:String;public let category:String;public let periods:[String];public let comparators:[String];public let kind:String;public let unit:String?;public let minimum:Double?;public let maximum:Double?;public let options:[String]?}
public struct GoalsPage:Codable,Sendable {public let goals:[Goal];public let targets:[GoalTarget]}
public struct HealthCapabilities:Codable,Sendable {public let apiVersions:[String];public let features:[String];public let metrics:[MetricDefinition]?;public let goalTargets:[GoalTarget]?}
public struct NextcloudCapabilities:Codable,Sendable {public let health:HealthCapabilities}
public struct CapabilitiesData:Codable,Sendable {public let capabilities:NextcloudCapabilities}
public struct GoalProgress:Codable,Identifiable,Sendable {public var id:Int64{goalId};public let goalId:Int64;public let targetKey:String;public let metricKey:String;public let period:String;public let currentValue:Double?;public let targetValue:Double;public let progressRatio:Double?;public let status:String}
public struct SavedStatisticsView:Codable,Identifiable,Sendable {public let id:Int64;public var title:String;public var icon:String;public var metricKeys:[String];public var period:String;public let createdAt:String?;public let updatedAt:String?}
public struct StatisticsPoint:Codable,Identifiable,Sendable {public var id:String{date};public let date:String;public let value:Double?;public let subseries:[String:Double?]?}
public struct StatisticsSummary:Codable,Sendable {public let average:Double?;public let minimum:Double?;public let maximum:Double?;public let count:Int;public let activeDays:Int;public let subseries:[String:StatisticsSubseriesSummary]?}
public struct StatisticsSubseriesSummary:Codable,Sendable {public let average:Double?;public let minimum:Double?;public let maximum:Double?;public let count:Int;public let activeDays:Int;public let subseries:JSONValue?}
public struct StatisticsGoalSegment:Codable,Identifiable,Sendable {public var id:String{"\(goalId)-\(effectiveFrom)"};public let goalId:Int64;public let targetKey:String;public let metricKey:String;public let kind:String;public let seriesKey:String?;public let comparator:String;public let targetValue:Double;public let options:[String]?;public let effectiveFrom:String;public let effectiveTo:String?}
public struct StatisticsMetric:Codable,Identifiable,Sendable {public var id:String{metricKey};public let metricKey:String;public let category:String;public let valueType:String;public let canonicalUnit:String?;public let minimum:Double?;public let maximum:Double?;public let series:[StatisticsPoint];public let summary:StatisticsSummary?;public let goals:[StatisticsGoalSegment]}
public struct StatisticsResponse:Codable,Sendable {public let period:String;public let from:String;public let to:String;public let metrics:[StatisticsMetric]}
public struct ProfileConfiguration:Codable,Sendable {public var heightCm:Double?;public var heightDisplayUnit:String?;public var dateOfBirth:String?;public var growthReferenceSex:String?}
public struct MetricConfiguration:Codable,Sendable {public var enabled:Bool;public var checkInEnabled:Bool;public var checkOutEnabled:Bool;public var displayUnit:String?}
public struct Configuration:Codable,Sendable {public var profile:ProfileConfiguration;public var metrics:[String:MetricConfiguration];public var searchDailyNotes:Bool}
public struct OutboxOperation:Codable,Identifiable,Equatable,Sendable {public enum State:String,Codable,Sendable{case pending,syncing,failed};public let operationId:UUID;public var id:UUID{operationId};public let createdAt:Date;public let endpoint:String;public let method:HTTPMethod;public let body:Data;public var attempts:Int;public var state:State;public var lastError:String?;public init(operationId:UUID=UUID(),createdAt:Date=Date(),endpoint:String,method:HTTPMethod,body:Data,attempts:Int=0,state:State = .pending,lastError:String?=nil){self.operationId=operationId;self.createdAt=createdAt;self.endpoint=endpoint;self.method=method;self.body=body;self.attempts=attempts;self.state=state;self.lastError=lastError}}
