// SPDX-License-Identifier: AGPL-3.0-or-later
import Foundation
import UIKit
import HealthCore
struct LoginFlowStart:Decodable {struct Poll:Decodable{let token:String;let endpoint:String};let poll:Poll;let login:String}
struct LoginFlowResult:Decodable {let server:String;let loginName:String;let appPassword:String}
struct Empty:Codable{}
actor HealthAPIClient {
 private let account:StoredAccount;private let server:ServerConfiguration;private let session:URLSession
 init(account:StoredAccount)throws{self.account=account;server=try .init(server:account.server);let c=URLSessionConfiguration.ephemeral;c.requestCachePolicy = .reloadIgnoringLocalCacheData;c.urlCache=nil;session=URLSession(configuration:c)}
 private var authorization:String{"Basic "+Data("\(account.login):\(account.appPassword)".utf8).base64EncodedString()}
 func send<T:Decodable>(_ endpoint:APIEndpoint,method:HTTPMethod = .get,body:Encodable?=nil,as:T.Type=T.self)async throws->T{let bodyData=try body.map{try JSONEncoder().encode(AnyEncodable($0))};let data=try await sendValidatedRaw(endpoint,method:method,body:bodyData);if T.self==Empty.self{return Empty() as! T};return try JSONDecoder.health.decode(OCSResponse<T>.self,from:data).ocs.data}
 func sendValidatedRaw(_ endpoint:APIEndpoint,method:HTTPMethod,body:Data?)async throws->Data{let data=try await sendRaw(endpoint,method:method,body:body);let envelope=try JSONDecoder.health.decode(OCSMetadataResponse.self,from:data);try envelope.ocs.meta.validate();return data}
 func sendRaw(_ endpoint:APIEndpoint,method:HTTPMethod,body:Data?)async throws->Data{let request=try RequestBlueprint(endpoint:endpoint,method:method,body:body).request(server:server,authorization:authorization);let(d,r)=try await session.data(for:request);guard let h=r as? HTTPURLResponse else{throw HealthCoreError.invalidResponse};if h.statusCode==401||h.statusCode==403{if try await checkRemoteWipe(){await MainActor.run{NotificationCenter.default.post(name:.remoteWipeRequired,object:nil)}};throw HealthCoreError.ocs(h.statusCode,"Authentication failed")};guard (200..<300).contains(h.statusCode)else{throw HealthCoreError.ocs(h.statusCode,"Nextcloud rejected the request")};return d}
 func capabilities()async throws->HealthCapabilities{let data:CapabilitiesData=try await send(.capabilities);return data.capabilities.health}
 func configuration()async throws->Configuration{try await send(.configuration)};func updateConfiguration(_ x:ConfigurationUpdate)async throws->Configuration{try await send(.configuration,method:.put,body:x)}
 func dailyNote(_ d:String)async throws->DailyNote{try await send(.dailyNote(d))};func updateDailyNote(_ d:String,content:String)async throws->DailyNote{try await send(.dailyNote(d),method:.put,body:["content":content])}
 func dailyValues(_ d:String)async throws->[DailyValue]{struct P:Decodable{let values:[DailyValue]};return try await send(.dailyValues(d),as:P.self).values};func putDailyValue(_ metric:String,date:String,value:Double,unit:String?)async throws->DailyValue{try await send(.dailyValue(metric:metric,date:date),method:.put,body:DailyValueInput(numericValue:value,unit:unit))};func deleteDailyValue(_ m:String,date:String)async throws->Empty{try await send(.dailyValue(metric:m,date:date),method:.delete)}
 func entries(_ q:EntryQuery)async throws->EntriesPage{try await send(.entries(q))};func allEntries(_ q:EntryQuery,maxPages:Int=100)async throws->[Entry]{var result:[Entry]=[];var query=q;query.limit=min(max(q.limit,1),200);for _ in 0..<maxPages{let page=try await entries(query);result.append(contentsOf:page.entries);guard let cursor=page.nextCursor,!cursor.isEmpty else{return result};query.cursor=cursor};throw HealthCoreError.invalidResponse};func createEntry(_ body:EntryInput)async throws->Entry{try await send(.entries(.init()),method:.post,body:body)};func updateEntry(_ id:Int64,_ body:EntryInput)async throws->Entry{try await send(.entry(id),method:.put,body:body)};func deleteEntry(_ id:Int64)async throws->Empty{try await send(.entry(id),method:.delete)}
 func measurements(from:String?=nil,to:String?=nil)async throws->[Measurement]{struct P:Decodable{let measurements:[Measurement]};return try await send(.measurements(from:from,to:to),as:P.self).measurements};func createMeasurement(_ b:MeasurementInput)async throws->Measurement{try await send(.measurements(from:nil,to:nil),method:.post,body:b)};func updateMeasurement(_ id:Int64,_ b:MeasurementInput)async throws->Measurement{try await send(.measurement(id),method:.put,body:b)};func deleteMeasurement(_ id:Int64)async throws->Empty{try await send(.measurement(id),method:.delete)}
 func routine(_ context:String,_ b:RoutineInput)async throws->JSONValue{try await send(.routine(context),method:.post,body:b)}
 func goals()async throws->GoalsPage{try await send(.goals)};func createGoal(_ b:GoalInput)async throws->Goal{try await send(.goals,method:.post,body:b)};func updateGoal(_ id:Int64,_ b:GoalInput)async throws->Goal{try await send(.goal(id),method:.put,body:b)};func deleteGoal(_ id:Int64)async throws->Empty{try await send(.goal(id),method:.delete)};func goalProgress(period:GoalPeriod,date:String?)async throws->[GoalProgress]{struct P:Decodable{let goals:[GoalProgress]};return try await send(.goalProgress(period:period,date:date),as:P.self).goals}
 func statistics(_ p:StatisticsPeriod,metrics:[String])async throws->StatisticsResponse{try await send(.statistics(period:p,metrics:metrics))};func views()async throws->[SavedStatisticsView]{struct P:Decodable{let views:[SavedStatisticsView]};return try await send(.statisticsViews,as:P.self).views};func createView(_ b:StatisticsViewInput)async throws->SavedStatisticsView{try await send(.statisticsViews,method:.post,body:b)};func updateView(_ id:Int64,_ b:StatisticsViewInput)async throws->SavedStatisticsView{try await send(.statisticsView(id),method:.put,body:b)};func deleteView(_ id:Int64)async throws->Empty{try await send(.statisticsView(id),method:.delete)}
 func removeAppPassword()async throws{var u=server.url;u.append(path:"ocs/v2.php/core/apppassword");var r=URLRequest(url:u);r.httpMethod="DELETE";r.setValue(authorization,forHTTPHeaderField:"Authorization");r.setValue("true",forHTTPHeaderField:"OCS-APIRequest");r.setValue("application/json",forHTTPHeaderField:"Accept");let(data,response)=try await session.data(for:r);guard (response as? HTTPURLResponse)?.statusCode==200 else{throw HealthCoreError.invalidResponse};let envelope=try JSONDecoder.health.decode(OCSMetadataResponse.self,from:data);try envelope.ocs.meta.validate()}
 private func checkRemoteWipe()async throws->Bool{struct Wipe:Decodable{let wipe:Bool};var u=server.url;u.append(path:"index.php/core/wipe/check");var r=URLRequest(url:u);r.httpMethod="POST";r.setValue("application/x-www-form-urlencoded",forHTTPHeaderField:"Content-Type");r.httpBody=Data(FormEncoding.field("token",value:account.appPassword).utf8);let(d,response)=try await session.data(for:r);guard (response as? HTTPURLResponse)?.statusCode==200,let result=try? JSONDecoder().decode(Wipe.self,from:d) else{return false};return result.wipe}
 func signalWipeSuccess()async{var u=server.url;u.append(path:"index.php/core/wipe/success");var r=URLRequest(url:u);r.httpMethod="POST";r.setValue("application/x-www-form-urlencoded",forHTTPHeaderField:"Content-Type");r.httpBody=Data(FormEncoding.field("token",value:account.appPassword).utf8);_ = try? await session.data(for:r)}
}
extension Notification.Name{static let remoteWipeRequired=Notification.Name("HealthJournal.remoteWipeRequired")}
struct AnyEncodable:Encodable{let f:(Encoder)throws->Void;init(_ x:Encodable){f=x.encode};func encode(to e:Encoder)throws{try f(e)}}
struct ConfigurationUpdate:Encodable{struct Profile:Encodable{var height:Double?;var heightUnit:String?;var dateOfBirth:String?;var growthReferenceSex:String?};var profile:Profile;var metrics:[String:MetricConfiguration];var searchDailyNotes:Bool}
struct DailyValueInput:Encodable{let numericValue:Double;let unit:String?};struct RoutineDailyValueInput:Encodable{let metricKey:String;let numericValue:Double;let unit:String?};struct EntryInput:Encodable{var metricKey:String;var numericValue:Double?;var optionValue:String?;var context:String;var recordedAt:String;var note:String?;var operationId:UUID?};struct MeasurementInput:Encodable{var metricKey:String;var numericValue:Double?;var values:[String:Double]?;var unit:String?;var context:String;var recordedAt:String;var note:String?;var operationId:UUID?};struct RoutineInput:Encodable{var date:String;var recordedAt:String;var journalMetrics:[EntryInput];var measurements:[MeasurementInput];var dailyValues:[RoutineDailyValueInput]};struct GoalInput:Encodable{var targetKey:String;var period:String;var comparator:String;var targetValue:Double;var active:Bool;var remindersEnabled:Bool};struct StatisticsViewInput:Encodable{var title:String;var icon:String;var metricKeys:[String];var period:String}
@MainActor enum NextcloudLoginFlow {
 static func start(server:ServerConfiguration)async throws->(LoginFlowStart,URLSession){let c=URLSessionConfiguration.ephemeral;let s=URLSession(configuration:c);let u=server.url.appending(path:"index.php/login/v2");var r=URLRequest(url:u);r.httpMethod="POST";let(d,response)=try await s.data(for:r);guard (response as? HTTPURLResponse)?.statusCode==200 else{throw HealthCoreError.invalidResponse};let start=try JSONDecoder().decode(LoginFlowStart.self,from:d);guard let login=URL(string:start.login)else{throw HealthCoreError.invalidResponse};UIApplication.shared.open(login);return(start,s)}
 static func poll(_ start:LoginFlowStart,session:URLSession,timeout:Duration = .seconds(300))async throws->LoginFlowResult{let clock=ContinuousClock();let deadline=clock.now.advanced(by:timeout);guard let u=URL(string:start.poll.endpoint),u.scheme=="https" else{throw HealthCoreError.insecureServer};while clock.now<deadline{var r=URLRequest(url:u);r.httpMethod="POST";r.setValue("application/x-www-form-urlencoded",forHTTPHeaderField:"Content-Type");r.httpBody=Data(FormEncoding.field("token",value:start.poll.token).utf8);let(d,res)=try await session.data(for:r);let status=(res as? HTTPURLResponse)?.statusCode;if status==200{return try JSONDecoder().decode(LoginFlowResult.self,from:d)};guard status==404 else{throw HealthCoreError.invalidResponse};try await Task.sleep(for:.seconds(1))};throw URLError(.timedOut)} }
